In [7]:
import numpy as np
import pandas as pd
from sklearn.datasets import make_regression

In [2]:
# setp 1 - Generate data

make_regression()

(array([[ 1.93481416,  0.22382256, -0.73626517, ...,  1.56695579,
         -0.81825813, -1.27121845],
        [-0.93685453,  0.04046543,  0.91596805, ...,  1.24560051,
          0.19964324, -1.44501622],
        [-1.2033063 ,  0.88485808, -0.80096774, ...,  2.0420634 ,
         -0.68651712, -0.94095709],
        ...,
        [-0.74037984, -0.55363581,  0.92332066, ...,  0.4340024 ,
         -0.24432192,  1.65373022],
        [-0.80424987, -0.91602855, -0.22903165, ...,  1.23828524,
          1.06825707, -0.8680294 ],
        [ 0.45393401, -1.2361705 ,  0.05173166, ..., -0.29978458,
          0.83467747, -0.7363208 ]]),
 array([  80.08914049,  320.73384751,  130.18971519, -177.01531417,
          76.54258343,  -58.60634141,  -44.52299688,  105.89761161,
        -189.7031271 , -232.79868661,    5.35177695, -144.5862385 ,
        -228.70785252,  -39.70274839,  -24.01213085, -206.03459394,
         240.13640981,  333.0304635 ,   84.32412093, -183.14710721,
        -179.18086354,  487.08778212,  723.79847527, -137.88932971,
          43.72236521,   48.74679162,  114.35876013, -205.56884961,
        -285.2126057 ,  425.21782665,  142.3266742 , -351.87011441,
        -182.61483592,   60.00352611, -217.71401388,  138.71843678,
         280.65575468,  136.66228216,   70.695749  ,   45.89995593,
        -101.51951776, -184.57670222,   -6.54014669,    6.7303386 ,
         344.93488697,  134.29749583,  310.5680584 ,  160.26235089,
        -148.21274   ,  283.80437729, -136.61461591,  -79.20944506,
        -202.21264931,  168.88165528, -262.44886369, -311.88853141,
         260.02762774, -310.52566636,  -32.72614997,  129.39944775,
        -359.68091668,  -16.33193477, -190.03252647,  116.7382012 ,
        -246.3637969 ,   31.89717475,   21.8207864 , -375.31838471,
         281.45354173,   34.81741364,   59.36410088,  182.25641353,
        -274.66556974,  -76.24367872,  -78.92595065,  -37.67547907,
        -388.63994516,    6.0742139 ,  172.83015334, -209.59365667,
          15.36208105, -158.02832768,  534.90196198, -231.39668127,
         -33.26840372,   40.15573344,   18.7992052 ,   51.5368015 ,
          26.41473124,  385.92529555,  -67.33457788,  236.45105377,
        -112.23296634,  -57.36528762,  264.5353809 , -309.88850125,
        -572.63101871, -116.82428752,  156.78527287, -187.03842688]))

In [4]:
X,y = make_regression()
print(X.shape,y.shape)

(100, 100) (100,)

In [5]:
X,y = make_regression(n_samples=500, n_features=10, n_informative=5, noise=25.8, random_state=0)
print(X.shape,y.shape)

(500, 10) (500,)

In [8]:
pd.DataFrame(X).head()

,0,1,2,3,4,5,6,7,8,9
0,1.706468,1.511639,-0.000417,0.374155,0.073285,0.701783,0.409552,-0.461894,-0.626490,-0.799593
1,-1.616956,0.640132,-0.369182,-0.239379,-0.738031,-0.024326,1.099660,0.279925,-0.098150,0.655264
2,0.093953,-0.130107,0.929505,0.582225,-2.739677,0.943046,-2.094603,-0.569312,0.269904,0.123722
3,-1.542758,-0.789954,0.537035,-0.286835,-2.369623,-0.767332,1.634406,-0.260560,0.128957,0.571227
4,-0.101003,-2.231538,0.436187,1.571463,1.324868,-0.587375,1.077315,0.840648,0.261106,0.811090

In [9]:
pd.DataFrame(X).head(n=100)

,0,1,2,3,4,5,6,7,8,9
0,1.706468,1.511639,-0.000417,0.374155,0.073285,0.701783,0.409552,-0.461894,-0.626490,-0.799593
1,-1.616956,0.640132,-0.369182,-0.239379,-0.738031,-0.024326,1.099660,0.279925,-0.098150,0.655264
2,0.093953,-0.130107,0.929505,0.582225,-2.739677,0.943046,-2.094603,-0.569312,0.269904,0.123722
3,-1.542758,-0.789954,0.537035,-0.286835,-2.369623,-0.767332,1.634406,-0.260560,0.128957,0.571227
4,-0.101003,-2.231538,0.436187,1.571463,1.324868,-0.587375,1.077315,0.840648,0.261106,0.811090
...,...,...,...,...,...,...,...,...,...,...
95,1.396849,2.123526,-0.104049,0.881225,0.374969,-0.432827,-0.088373,0.494445,0.761391,0.267671
96,-0.954943,0.100564,1.102283,-0.697073,1.010428,-1.470402,0.207334,0.496179,0.576956,0.759157
97,0.715939,0.542611,0.147434,-0.977465,0.880938,-2.994613,0.879390,1.808132,0.436638,0.635425
98,-0.177813,-1.892362,1.905064,-0.014777,1.054758,0.250998,-0.300479,0.960048,-0.416499,-0.355029
99,0.477068,-0.968082,0.623454,0.890672,2.540232,-0.355951,0.512917,0.926558,0.558082,-2.541239

In [10]:
# step 2 - normalise

In [12]:
X.mean(axis=0).shape

(10,)

In [13]:
def normalise(X):
    u = X.mean(axis=0)
    std = X.std(axis=0)

    return (X-u)/std

In [ ]:
X